
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "naelyn/ubuntu-trusty64-libvirt"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.define "onefrontend414" do |onefrontend414|
    onefrontend414.vm.hostname="onefrontend414"
    onefrontend414.vm.network :private_network, :ip => "192.168.50.200"
    onefrontend414.vm.provision "shell", path: "sharedstuff/onegeneric.sh"
    onefrontend414.vm.provider :libvirt do |domain|
      domain.memory = 512
      domain.cpus = 2
      domain.nested = true
    end
  end
  config.vm.define "hypervisor1414" do |hypervisor1414|
    hypervisor1414.vm.hostname="hypervisor1414"
    hypervisor1414.vm.network :private_network, :ip => "192.168.50.201"
    hypervisor1414.vm.provision "shell", path: "sharedstuff/onegeneric.sh"
    hypervisor1414.vm.provider :libvirt do |domain|
      domain.memory = 2048
      domain.cpus = 3
      domain.nested = true
    end
  end
  config.vm.define "hypervisor2414" do |hypervisor2414|
    hypervisor2414.vm.hostname="hypervisor2414"
    hypervisor2414.vm.network :private_network, :ip => "192.168.50.202"
    hypervisor2414.vm.provision "shell", path: "sharedstuff/onegeneric.sh"
    hypervisor2414.vm.provider :libvirt do |domain|
      domain.memory = 2048
      domain.cpus = 3
      domain.nested = true
    end
  end
end
