version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - 6379
  db:
    image: postgres
    expose:
      - 5432
  web:
    links:
      - db
      - redis
    build: .
    command: /usr/bin/supervisord -n
    volumes:
      - ../../ssddj:/code
      - ./appdata:/data
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
